global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9093']

  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8000']

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8080']

